sudo: required
services:
  - docker

before_install:
  - docker build -t kovacevicdenis/docker-react -f Dockerfile.dev .

script:
  - docker run kovacevicdenis/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "denisdev-docker-react"
  env: "DenisdevDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-198205498207"
  bucket_path: "denisdev-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"